# Windows PowerShell unit test.
filegroup(
    name = "powershell_scripts",
    srcs = [
        "hyperv_host.Tests.ps1",
        "kaspersky_av_client.Tests.ps1",
        "mk_inventory.Tests.ps1",
        "windows_updates.Tests.ps1",
    ],
    tags = ["lint-with-psscriptanalyzer"],
)
