type = "Component"
display_name = "UI - Navigation & Sidebar"
has_support_component = true
members_required = 2
description = """
- The main navigation and the sidebar (snapins, quick search, ...)
"""
