/**
 * Copyright (C) 2026 Checkmk GmbH - License: GNU General Public License v2
 * This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
 * conditions defined in the file COPYING, which is part of this source code package.
 */

/**
 * Flamegraph canvas painting constants.
 *
 * The rect fills generated by ``nameColor`` below are theme-independent pastel
 * colors, so the label / overlay / border colors painted on top must be
 * theme-independent as well — a dark-theme "label color" would be unreadable
 * on the light pastels, and vice versa. All painting constants live here so
 * the "intentionally not theme-switched" contract lives in one place.
 */
export const RECT_LABEL_COLOR_PRIMARY = '#1a1a1a'
export const RECT_LABEL_COLOR_SECONDARY = 'rgba(40, 40, 40, 0.85)'
export const RECT_HOVER_OVERLAY = 'rgba(255, 255, 255, 0.35)'
export const RECT_THIN_BORDER = 'rgba(0, 0, 0, 0.2)'

/** Canvas 2D context line widths — not expressible as CSS tokens. */
export const HIGHLIGHT_STROKE_WIDTH = 2.5
export const THIN_BORDER_WIDTH = 0.5

/**
 * Heat color from yellow (low) through orange to red (high).
 * Used for both flamegraph frames and hotspot table indicators.
 * Returns CSS var() references so colors follow the active theme.
 */
export function heatColor(pct: number): string {
  if (pct > 20) {
    return 'var(--color-light-red-60)'
  }
  if (pct > 5) {
    return 'var(--color-orange-60)'
  }
  return 'var(--color-yellow-60)'
}

const nameColorCache = new Map<string, string>()

// Curated hue buckets drawn from the Checkmk palette — yellow, orange, cyan,
// light-blue, corporate-green, purple, pink. Restricting to these keeps the
// flamegraph on-brand vs. a full 0–359 hue spectrum.
const PALETTE_HUES = [48, 32, 185, 210, 158, 245, 325]

/**
 * Deterministic color from function name.
 * Same function always gets the same color, regardless of timing.
 * Results are cached since this is called per frame per draw.
 */
export function nameColor(name: string): string {
  const cached = nameColorCache.get(name)
  if (cached !== undefined) {
    return cached
  }
  let hash = 5381
  for (let i = 0; i < name.length; i++) {
    hash = ((hash << 5) + hash + name.charCodeAt(i)) & 0xffffffff
  }
  const bucket = (hash >>> 0) % PALETTE_HUES.length
  const baseHue = PALETTE_HUES[bucket]!
  const hueJitter = ((hash >>> 4) % 11) - 5
  const hue = (baseHue + hueJitter + 360) % 360
  const sat = 40 + ((hash >>> 8) % 15)
  const lit = 72 + ((hash >>> 16) % 10)
  const color = `hsl(${hue}, ${sat}%, ${lit}%)`
  nameColorCache.set(name, color)
  return color
}
