load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//bazel/rules:doctest.bzl", "py_doc_test")

py_library(
    name = "agents",
    srcs = ["mk_filestats.py"],
    visibility = [
        "//cmk/plugins:__subpackages__",
        "//tests:__subpackages__",
    ],
)

py_doc_test(
    name = "doctest",
    size = "small",
    srcs = [":agents"],
)
